modifiers = {
      'Hot Chocolate': {
            'Mint': 'Hot Chocolate Mint',
            'Strawberry': 'Hot Chocolate Berry',
      },
      'Iced Chocolate': {
            'Mint': 'Iced Chocolate Mint',
            'Strawberry': 'Iced Chocolate Berry',
      },
      'Iced Chocolate Large': {
            'Mint': 'Iced Chocolate Mint Large',
            'Strawberry': 'Iced Chocolate Berry Large',
      },
      'Pisang': {
            'Keju': 'Pisang Keju',
      },
}


menu_print_list_foods = [
    'Espresso (Single Shot)',
    'Hot Americano',
    'Iced Americano',
    'Iced Americano Large',
    'Hot Cappuccino',
    'Iced Cappuccino',
    'Iced Cappuccino Large',
    'Hot Cappuccino Butterscotch',
    'Iced Cappuccino Butterscotch',
    'Iced Cappuccino Butterscotch Large',
    'Hot Cappuccino Hazelnut',
    'Iced Cappuccino Hazelnut',
    'Iced Cappuccino Hazelnut Large',
    'Hot Cappuccino Gula Aren',
    'Iced Cappuccino Gula Aren',
    'Iced Cappuccino Gula Aren Large',
    'Hot Latte',
    'Iced Latte',
    'Iced Latte Large',
    'Hot Latte Butterscotch',
    'Iced Latte Butterscotch',
    'Iced Latte Butterscotch Large',
    'Hot Latte Hazelnut',
    'Iced Latte Hazelnut',
    'Iced Latte Hazelnut Large',
    'Coffee Milk Butterscotch',
    'Coffee Milk Butterscotch Large',
    'Coffee Milk Gula Aren',
    'Coffee Milk Gula Aren Large',
    'Coffee Milk Hazelnut',
    'Coffee Milk Hazelnut Large',
    'Con Heiloo',
    'Affogato',
    'Hot Chocolate',
    'Iced Chocolate',
    'Iced Chocolate Large',
    'Iced Chocolate Mint',
    'Iced Chocolate Mint Large',
    'Iced Chocolate Berry',
    'Iced Chocolate Berry Large',
    'Hot Matcha',
    'Iced Matcha',
    'Iced Matcha Large',
    'Iced Red Velvet',
    'Iced Red Velvet Large',
    'Iced Taro',
    'Iced Taro Large',
    'Cocomoon',
    'Mojito',
    'Strawberry Milkshake',
    'Summer Passion',
    'Tropical Berries',
    'Vanilla Regal',
    'Cookies n’ Cream',
    'V60',
    'Japanese',
    'Vietnam Drip',
    'Hot Tea',
    'Iced Tea',
    'Hot Lemon Tea',
    'Iced Lemon Tea',
    'Iced Lemon Tea Large',
    'Lychee Tea',
    'Lychee Tea Large',
    'Thai Tea',
    'Thai Tea Large',
    'Mineral Water',
]

menu_print_list_beverages = [
    'Kentang Sosis',
    'Pisang',
    'Pisang Keju',
    'Tahu Cabai Garam',
    'Classic Burger',
    'Rice Bowl Sambal Matah',
    'Rice Bowl Black Pepper',
    'Rice Bowl Teriyaki',
    'Rice Bowl Yakiniku',
    'Spaghetti Carbonara',
    'Spaghetti Aglio e Olio',
    'Mie Goreng',
    'Mie Kuah',
    'Nasi Goreng',
    'Waffle',
    'Pancake',
]